name: default

on:
  push:
  repository_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Fatmouse branch: ${{ github.event.client_payload.repository }}"
