name: default

on:
  push:
  repository_dispatch:

jobs:
  downstream:
    runs-on: ubuntu-latest
    steps:
      - name: Setup upstream
        if: github.event.action == 'upstream_push'
        run: |
          echo "Create check-runs for the upstream"
          curl -u ${{ secrets.GITHUB_TOKEN }} \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/vmotso-labs/like_fatmouse/check-runs \
          -d '{"name":"test","head_sha":"b1ceeb7bfba55dd5796dc4adb28da6e8feac6a81"}'
      - name: Verify event
        run: |
          echo "Fatmouse branch: ${{ github.event.client_payload.branch }}"
