name: Workflow triggered by upstream
on:
  workflow_dispatch:
    inputs:
      api_branch:
        description: "API Branch"
        required: true
      db_branch:
        description: "DB Branch"
        required: false
        default: "master"
      upstream_sha:
        description: "DB Branch"
        required: true
jobs:
  acc-tests:
    env:
      API_BRANCH: ${{ github.event.inputs.api_branch }}
      DB_BRANCH: ${{ github.event.inputs.db_branch }}
      UPSTREAM_SHA: ${{ github.event.inputs.upstream_sha }}
      ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
    runs-on: ubuntu-latest
    name: acc-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: Run acceptance tests
        run: |
          echo "Acceptance tests"
          sleep 60
      - name: Notify upstream aboute success
        if: ${{ success() }}
        run: ./notify_upstream.sh success
      - name: Notify upstream aboute failure
        if: ${{ failure() }}
        run: ./notify_upstream.sh failure
